### ISSUE TITLE
Unselected current day 

### ISSUE THREAD

**Issue by epos38** [dubrox/Multiple-Dates-Picker-for-jQuery-UI#148]
Hello,

I am looking to a solution to unselect the current day by default when i use date time peaker.
WHen I select a random date, the current date is selected automatically. I want to disable this action.

Can you please advise me how can I do.

Thanks for your help,

Regards,

**Comment by Asinox** [comment]
Any update about this?

**Comment by JamesNock** [comment]
I also want todays date to not autoselect too!

**Comment by pydolan** [comment]
I vaguely remember there being an issue where selected days and the current day using the same css style.  Could this be what you're seeing, or are you actually getting the current day when you call the get-dates API?

**Comment by JamesNock** [comment]
Thanks for the mega-quick response! Today’s cell is automatically getting a class of 'ui-state-highlight’ added to it which is what’s making it appear selected. Any ideas?

**Comment by pydolan** [comment]
Yes, I use the following CSS to avoid this problem (at least I think this is what I wrote the CSS for -- again, I haven't looked at this for a bit):

```css
#my-dup-day-picker a.ui-state-active {
  border-color: #c5c5c5;
  background-color: #f6f6f6;
  color: #454545;
}

#my-dup-day-picker .ui-state-highlight {
  border: 0;
}

#my-dup-day-picker .ui-state-highlight a {
  background-color: #fff7cc;
  border-color: #ffd700;
  color: #777620;
}
```

(Some of the css may not be applicable, but hopefully it gets you close to where you want)
